spring:
  application:
    name: demo1
  # H2 콘솔 활성화 (반드시 spring: 바로 아래, 2칸 들여쓰기)
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        web-allow-others: true

  # DB 연결 설정
  datasource:
    url: jdbc:postgresql://localhost:5432/main_db
    username: postgres # 혹은 새로 만든 유저
    password: admin
    driver-class-name: org.postgresql.Driver
  # JPA 및 하이버네이트 설정
#  jpa:
#    defer-datasource-initialization: true
#    hibernate:
#      ddl-auto: update
#    show-sql: true
  jpa:
    hibernate:
      ddl-auto: update # 테이블이 없으면 생성, 있으면 구조 수정
    show-sql: true     # 실행되는 SQL을 콘솔에 출력 (디버깅용)
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.demo.dto

  configuration:
    map-underscore-to-camel-case: true # DB 컬럼명(snake_case)을 Java 필드(camelCase)로 자동 매핑
    jdbc-type-for-null: OTHER # PostgreSQL의 JSONB/UUID 처리를 위해 필수
# Ollama 설정
  ai:
   ollama:
      base-url: http://suhmac.local:11434
      chat:
        options:
         model:gemma2

# 최상위 계층
comfyui:
  base-url: http://suh.local:8188

server:
  port: 8080

