# Ollama API (localhost:11434)
ollama.base-url=http://localhost:11434
ollama.default-model=my-eeve

# ComfyUI API (localhost:8188)
comfyui.base-url=http://localhost:8188
comfyui.workflow-resource=workspace/testWF22.json
comfyui.poll.max-seconds=120
comfyui.poll.interval-ms=1000

# H2 Console \uC124\uC815 (\uBE0C\uB77C\uC6B0\uC800\uC5D0\uC11C DB \uD655\uC778\uC6A9)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# DB \uC5F0\uACB0 \uC815\uBCF4
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA \uC124\uC815
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true